import {StyleSheet} from 'react-native';
import {appColors} from '../../../utils/appColors';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: appColors.transparent,
  },
  imageProfile: {flex: 1, width: 300, height: 300, borderRadius: 150},
  image: {flex: 1, width: 300, height: 300},
  titleBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 24,
    marginHorizontal: 16,
  },
  txtComSub: {
    fontFamily: 'HelveticaNeue',
    color: appColors.secondClaro,
    textTransform: 'uppercase',
    fontWeight: '500',
    fontSize: 12,
  },
  text: {fontFamily: 'HelveticaNeue', color: appColors.secondClaro},
  text300: {
    fontFamily: 'HelveticaNeue',
    color: appColors.secondClaro,
    fontWeight: '300',
  },
  text12: {
    fontFamily: 'HelveticaNeue',
    fontSize: 12,
    color: appColors.secondClaro,
    textTransform: 'uppercase',
  },
  text24: {
    fontFamily: 'HelveticaNeue',
    fontSize: 24,
    color: appColors.secondClaro,
  },
  text24Dif: {
    fontFamily: 'HelveticaNeue',
    fontSize: 24,
    color: appColors.secondClaro,
    fontWeight: '300',
  },
  subText: {
    color: appColors.secondClaro,
    textTransform: 'uppercase',
    fontWeight: '500',
    fontSize: 12,
  },
  subTextRecent: {
    color: appColors.secondClaro,
    textTransform: 'uppercase',
    fontWeight: '500',
    marginLeft: 78,
    marginTop: 32,
    marginBottom: 6,
    fontSize: 10,
  },
  profileImage: {
    width: 200,
    height: 200,
    borderRadius: 100,
    overflow: 'hidden',
  },
  dm: {
    backgroundColor: appColors.secondClaro,
    position: 'absolute',
    top: 20,
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  active: {
    backgroundColor: '#34FFB9',
    position: 'absolute',
    bottom: 28,
    left: 10,
    padding: 4,
    height: 20,
    width: 20,
    borderRadius: 10,
  },
  add: {
    backgroundColor: appColors.secondClaro,
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 60,
    height: 60,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  infoContainer: {alignSelf: 'center', alignItems: 'center', marginTop: 16},
  statsContainer: {flexDirection: 'row', alignSelf: 'center', marginTop: 32},
  statsBox: {alignItems: 'center', flex: 1},
  statsBoxAlt: {
    alignItems: 'center',
    flex: 1,
    borderColor: appColors.secondClaro,
    borderLeftWidth: 1,
    borderRightWidth: 1,
  },
  mediaImageContainer: {
    width: 150,
    height: 150,
    borderRadius: 12,
    overflow: 'hidden',
    marginHorizontal: 10,
  },
  mediaCount: {
    backgroundColor: appColors.third,
    position: 'absolute',
    top: '50%',
    marginTop: -50,
    marginLeft: 30,
    width: 100,
    height: 100,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    shadowColor: 'rgba(0,0,0,0.38)',
    shadowOffset: {width: 0, height: 10},
    shadowRadius: 20,
    shadowOpacity: 1,
  },
  recent: {marginLeft: 78, marginTop: 32, marginBottom: 6, fontSize: 10},
  recentItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 16,
  },
  recentItemIndicator: {
    backgroundColor: appColors.secondClaro,
    padding: 4,
    height: 12,
    borderRadius: 6,
    width: 12,
    marginTop: 3,
    marginRight: 20,
  },
});
